### PR TITLE
Fix preferences menu for firetv

### PR DESCRIPTION
**Pull request by pforemanpf**
Fire TV refuses to render the preferences page unless there is an intent defined.  Setting this config will let the preference page load.

Tested on Fire TV and android avd emulator

### CODE REVIEW

**Comment by stuckless** [comment]
In reviewing this, it would appear this is creating a full launcher for the SettingsActivity.  This means it'll get an icon on the home screen, etc.  not sure that is what what we want.  Could you you point me to documentation where FireTV says this is required?

I'm wondering if it's just the Theme Stuff that it needs, and the <intent-filter> can be removed.

**Comment by pforemanpf** [comment]
You are probably right, I was trying to run:
adb shell am start -n sagex.miniclient.android/.SettingsActivity
to force the activity to show up and this allowed that to start.  
I will play around with some other options tonight and see if I can choose one other than main/launcher and still get it to work.

**Comment by stuckless** [comment]
So to clarify, if you select the Preferences item from the list of servers, it just dies?  I would try to just add the Theme properties, and remove the intent filters, since, I can't imagine they'd be needed, except to launch it as a main activity, which isn't needed.

**Comment by pforemanpf** [comment]
Yes, it kicks me back to the fire tv application screen.  I'll try the theme tonight first and see if that does the trick.  That's what I get for rushing through a fix :)

**Pull request closed without merging**
